Welcome page works
Terria does not render due to expecting it to be at / instead of /explore
Jupyter:
1. Can login
2. import ewatercycle fails with

---> 11     from fiona.ogrext import Iterator, ItemsIterator, KeysIterator
     12     from fiona.ogrext import Session, WritingSession
     13     from fiona.ogrext import buffer_to_virtual_file, remove_virtual_file, GEOMETRY_TYPES

ImportError: libmpi.so.12: cannot open shared object file: No such file or directory