ESMpy needs env var
Got:
```
File /opt/conda/envs/ewatercycle/lib/python3.10/site-packages/esmpy/interface/loadESMF.py:28
     26     esmfmk = os.environ["ESMFMKFILE"]
     27 except:
---> 28     raise ImportError('The ESMFMKFILE environment variable is not available.')
     30 #### INVESTIGATE esmf.mk ######################################################
     31
     32 # TODO: look for various dependecies in the ESMF build log
   (...)
     37 #       use this information to set variables that can be checked at beginning
     38 #       of the routines that require an ESMF build with these dependencies
     40 with open(esmfmk, 'r') as MKFILE:
     41
     42     # investigate esmf.mk

ImportError: The ESMFMKFILE environment variable is not available.
```